### ISSUE TITLE
Add volume to wordpress image: docker compose 

### ISSUE THREAD

**Issue by grumpyp** [grumpyp/blogging-with-ai#1]
Instead of manually changing the .htaccess in the docker container, add a .htaaccess which maps it to the `/var/www/html` directory in the container itself. 

pseudo code 

```
version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./htaccess:/var/www/html/.htaccess

```
